### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by stleon** [aTastyCookie/yandexmoney_django#11]
Когда оплачиваю в тестовом магазине, на почту приходит следующее. Яндекс же пишет, что сервер не доступен.
```
Internal Server Error: /yandex-money/check/
Traceback (most recent call last):
 File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
   return self.dispatch(request, *args, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 29, in _wrapper
   return bound_func(*args, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
   return view_func(*args, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 25, in bound_func
   return func.__get__(self, type(self))(*args2, **kwargs2)
 File "/usr/local/lib/python2.7/dist-packages/yandex_money/views.py", line 36, in dispatch
   return super(BaseView, self).dispatch(*args, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
   return handler(request, *args, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/yandex_money/views.py", line 64, in post
   settings.get('YANDEX_MONEY_MAIL_ADMINS_ON_PAYMENT_ERROR', True) and
 File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 47, in __getattr__
   return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'get'
```

**Comment by stleon** [comment]
Чинится так:
```
getattr(settings, "YANDEX_MONEY_MAIL_ADMINS_ON_PAYMENT_ERROR", True)
```
